# Example TinyETL configuration file
version: 1

source:
  uri: "mysql://user:${MYSQL_PASS}@localhost:3306/salesdb#orders"

target:
  uri: "s3://${AWS_BUCKET}/exports/orders.parquet?access_key=${AWS_ACCESS_KEY_ID}&secret_key=${AWS_SECRET_ACCESS_KEY}&region=us-east-1"

options:
  batch_size: 50000
  infer_schema: true
  transform: |
    profit = row.revenue - row.cost
    margin = profit / row.revenue
  preview: 10
